"""
Django settings for safari_joint project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
import logging
import os
import sys
from easy_thumbnails.conf import settings as thumbnail_settings


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))

PROJECT_DIR  = os.path.dirname(__file__)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@ywfy6%%*08r7*5@iq-xsvc2n#yf6@vy6i(*3&@6w4-7t!&)kg'


# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = False

#ALLOWED_HOSTS = ['*']

DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'safari_joint',
    'django_countries',
    'phonenumber_field',
    'vote',
    'image_cropping',
    'easy_thumbnails',
    'crispy_forms',
    'formtools'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'safari_joint.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
#        'DIRS': [],
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            'C:\\Users\\AfricaTechSolutions\\Envs\\africatechsolutions\\safari_joint\\templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

TEMPLATES_DIRS = (
#    '/home/africatechsolutions/djangoivan/mainproject/templates'
    os.path.join(BASE_DIR, 'templates')
)

WSGI_APPLICATION = 'safari_joint.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'UTC'

TIME_ZONE = 'Africa/Dar_es_Salaam'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_ROOT = os.path.join(PROJECT_DIR)

STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'static/media')

MEDIA_URL  = '/media/'

STATICFILES_DIRS=(
(os.path.join(BASE_DIR, 'static')),
)


if DEBUG:
    EMAIL_HOST = 'localhost'
    EMAIL_PORT = 1025
    EMAIL_HOST_USER = ''
    EMAIL_HOST_PASSWORD = ''
    EMAIL_USE_TLS = False
    DEFAULT_FROM_EMAIL = 'testing@example.com'

THUMBNAIL_PROCESSORS = (
    'image_cropping.thumbnail_processors.crop_corners',
) + thumbnail_settings.THUMBNAIL_PROCESSORS

IMAGE_CROPPING_SIZE_WARNING = True


#try:
#    import django_extensions
#except ImportError:
#    pass
#else:
#    INSTALLED_APPS += ['django_extensions']


# disable logging while testing
#if len(sys.argv) > 1 and sys.argv[1] == 'test':
#    logging.disable(logging.CRITICAL)
    # use an in-memory db while testing
#    DATABASES['default']['NAME'] = ':memory:'


IMAGE_CROPPING_THUMB_SIZE = (300, 300)
#IMAGE_CROPPING_JQUERY_URL = 'js/jquery.min.js'
#IMAGE_CROPPING_JQUERY_URL = os.path.join(BASE_DIR, 'static/js/cropper-js/jquery.min.js')
#IMAGE_CROPPING_JQUERY_URL = None
THUMBNAIL_DEBUG = True
#HEADLESS = True

CRISPY_TEMPLATE_PACK = 'bootstrap3'
