# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import image_cropping.fields
import phonenumber_field.modelfields
import safari_joint.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccomodationBookingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_serial_number', models.CharField(blank=True, default=safari_joint.models.random_booking_chars, max_length=30, null=True)),
                ('reservation_placed_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('depature_date', models.DateField(blank=True, null=True)),
                ('your_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableAccomodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_serial_number', models.CharField(blank=True, default=safari_joint.models.get_random_chars, help_text=b'Do not Edit the value of this Field Unless it Brings Errors!', max_length=20, null=True, unique=True)),
                ('accomodation_type', models.CharField(choices=[(b'Single', b'Single'), (b'Double', b'Double'), (b'Triple', b'Triple'), (b'Quad', b'Quad'), (b'Queen', b'Queen'), (b'King', b'King'), (b'Twin', b'Twin'), (b'Double-double', b'Double-double'), (b'Studio', b'Studio'), (b'Mini-Suite', b'Mini-Suite'), (b'Suite', b'Suite'), (b'Connecting rooms', b'Connecting rooms'), (b'Adjoining rooms', b'Adjoining rooms'), (b'Adjacent rooms', b'Adjacent rooms')], default=b'Single', max_length=50)),
                ('available_space', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('price_USD', models.IntegerField(blank=True, null=True)),
                ('noise_level', models.CharField(choices=[(b'Loud', b'Loud'), (b'Quite', b'Quite'), (b'Sound Proof', b'Sound Proof')], default=b'Quite', max_length=50)),
                ('airport_transport', models.BooleanField(default=False)),
                ('is_updated', models.BooleanField(default=False)),
                ('original_price', models.IntegerField(blank=True, null=True)),
                ('room_updated_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FeedsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_posted_on', models.DateTimeField(auto_now_add=True)),
                ('feed_body', models.CharField(help_text=b'shortly as you can!', max_length=1000)),
                ('posted_by', models.CharField(max_length=200)),
                ('visit_date', models.DateField(blank=True, help_text=b'When Did you visit or use the services of this company?', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FunPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'cropped_images')),
                ('cropping', image_cropping.fields.ImageRatioField(b'image', '430x360', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping')),
            ],
        ),
        migrations.CreateModel(
            name='PageContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_main_heding', models.CharField(blank=True, default=b'This is a page', max_length=100, null=True)),
                ('page_head_introduction', models.CharField(max_length=1000)),
                ('page_main_content', models.CharField(blank=True, max_length=1000, null=True)),
                ('page_home_picture_one', models.ImageField(blank=True, help_text=b'This is a slide picture upload a picture of size 1600*600 or 1900*750 for home page', null=True, upload_to=safari_joint.models.page_images)),
                ('page_home_picture_two', models.ImageField(blank=True, help_text=b'This is a slide picture upload a picture of size 1600*600 or 1900*750 for home page', null=True, upload_to=safari_joint.models.page_images)),
                ('page_home_picture_three', models.ImageField(blank=True, help_text=b'This is a slide picture upload a picture of size 1600*600 or 1900*750 for home page', null=True, upload_to=safari_joint.models.page_images)),
                ('page_sub_heading_picture', models.ImageField(blank=True, help_text=b'This is an ordinary page picture upload a picture of size 550*480 or 560*209 for home page', null=True, upload_to=safari_joint.models.page_images)),
                ('page_sub_heading_picture_2', models.ImageField(blank=True, help_text=b'This is an ordinary page picture upload a picture of size 550*480 or 560*209 for home page', null=True, upload_to=safari_joint.models.page_images)),
                ('page_sub_heading_one', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_heading_content_one', models.CharField(blank=True, max_length=1000, null=True)),
                ('page_sub_heading_two', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_heading_content_two', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerGalleryPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('picture', models.ImageField(upload_to=safari_joint.models.partner_logo)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'partner_logo')),
                ('cropping', image_cropping.fields.ImageRatioField(b'image', '430x360', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping')),
            ],
        ),
        migrations.CreateModel(
            name='PartnersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_established_on', models.DateField()),
                ('company_nature', models.CharField(choices=[(b'Tour Operator', b'Tour Operator'), (b'Accomodation', b'Accomodation')], default=b'FIRST_TYPE', max_length=50)),
                ('company_location', models.CharField(choices=[(b'Arusha Region', b'Arusha Region'), (b'Dar es Salaam Region', b'Dar es Salaam Region'), (b'Dodoma Region', b'Dodoma Region'), (b'Geita Region', b'Geita Region'), (b'Iringa Region', b'Iringa Region'), (b'Kagera Region', b'Kagera Region'), (b'Katavi Region', b'Katavi Region'), (b'Kigoma Region', b'Kigoma Region'), (b'Kilimanjaro Region', b'Kilimanjaro Region'), (b'Lindi Region', b'Lindi Region'), (b'Manyara Region', b'Manyara Region'), (b'Mara Region', b'Mara Region'), (b'Mbeya Region', b'Mbeya Region'), (b'Morogoro Region', b'Morogoro Region'), (b'Mtwara Region', b'Mtwara Region'), (b'Mwanza Region', b'Mwanza Region'), (b'Njombe Region', b'Njombe Region'), (b'Pwani Region', b'Pwani Region'), (b'Rukwa Region', b'Rukwa Region'), (b'Ruvuma Region', b'Ruvuma Region'), (b'Shinyanga Region', b'Shinyanga Region'), (b'Simiyu Region', b'Simiyu Region'), (b'Singida Region', b'Singida Region'), (b'Tabora Region', b'Tabora Region'), (b'Tanga Region', b'Tanga Region'), (b'Zanzibar', b'Zanzibar')], default=b'Zanzibar', max_length=50)),
                ('company_review', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'partner_logo')),
                ('cropping', image_cropping.fields.ImageRatioField(b'image', '300x300', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping')),
                ('about_company', models.CharField(max_length=10000)),
                ('company_website', models.URLField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_on', models.DateTimeField(blank=True, null=True)),
                ('originally_registed_as', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('service_status', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_heading', models.CharField(max_length=100)),
                ('team_image_one', models.ImageField(blank=True, help_text=b'This is a slide picture upload a picture of size 250*190 or icon of size 78*78', null=True, upload_to=safari_joint.models.page_images)),
                ('team_heading_one', models.CharField(blank=True, max_length=100, null=True)),
                ('team_content_one', models.CharField(blank=True, max_length=1000, null=True)),
                ('team_url_one', models.CharField(blank=True, max_length=100, null=True)),
                ('team_image_two', models.ImageField(blank=True, help_text=b'This is a slide picture upload a picture of size 250*190 or icon of size 78*78', null=True, upload_to=safari_joint.models.page_images)),
                ('team_heading_two', models.CharField(blank=True, max_length=100, null=True)),
                ('team_content_two', models.CharField(blank=True, max_length=1000, null=True)),
                ('team_url_two', models.CharField(blank=True, max_length=100, null=True)),
                ('team_image_three', models.ImageField(blank=True, help_text=b'This is a slide picture upload a picture of size 250*190 or icon of size 78*78', null=True, upload_to=safari_joint.models.page_images)),
                ('team_heading_three', models.CharField(blank=True, max_length=100, null=True)),
                ('team_content_three', models.CharField(blank=True, max_length=1000, null=True)),
                ('team_url_three', models.CharField(blank=True, max_length=100, null=True)),
                ('team_image_four', models.ImageField(blank=True, help_text=b'This is a slide picture upload a picture of size 250*190 or icon of size 78*78', null=True, upload_to=safari_joint.models.page_images)),
                ('team_heading_four', models.CharField(blank=True, max_length=100, null=True)),
                ('team_content_four', models.CharField(blank=True, max_length=1000, null=True)),
                ('team_url_four', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripAvailableDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('trip_serial', models.CharField(blank=True, default=safari_joint.models.get_random_chars, help_text=b'Do not Edit the value of this Field Unless it Brings Errors!', max_length=20, null=True, unique=True)),
                ('depature_date', models.DateField(blank=True, null=True)),
                ('returning_date', models.DateField(blank=True, null=True)),
                ('trip_price', models.IntegerField(blank=True, null=True)),
                ('trip_location', models.CharField(choices=[(b'Arusha Region', b'Arusha Region'), (b'Dar es Salaam Region', b'Dar es Salaam Region'), (b'Dodoma Region', b'Dodoma Region'), (b'Geita Region', b'Geita Region'), (b'Iringa Region', b'Iringa Region'), (b'Kagera Region', b'Kagera Region'), (b'Katavi Region', b'Katavi Region'), (b'Kigoma Region', b'Kigoma Region'), (b'Kilimanjaro Region', b'Kilimanjaro Region'), (b'Lindi Region', b'Lindi Region'), (b'Manyara Region', b'Manyara Region'), (b'Mara Region', b'Mara Region'), (b'Mbeya Region', b'Mbeya Region'), (b'Morogoro Region', b'Morogoro Region'), (b'Mtwara Region', b'Mtwara Region'), (b'Mwanza Region', b'Mwanza Region'), (b'Njombe Region', b'Njombe Region'), (b'Pwani Region', b'Pwani Region'), (b'Rukwa Region', b'Rukwa Region'), (b'Ruvuma Region', b'Ruvuma Region'), (b'Shinyanga Region', b'Shinyanga Region'), (b'Simiyu Region', b'Simiyu Region'), (b'Singida Region', b'Singida Region'), (b'Tabora Region', b'Tabora Region'), (b'Tanga Region', b'Tanga Region'), (b'Zanzibar', b'Zanzibar')], default=b'Zanzibar', max_length=50)),
                ('about_trip', models.CharField(blank=True, max_length=3000, null=True)),
                ('is_udated', models.BooleanField(default=False)),
                ('trip_updated_on', models.DateTimeField(blank=True, null=True)),
                ('trip_original_name', models.CharField(blank=True, max_length=100, null=True)),
                ('trip_original_price', models.IntegerField(blank=True, null=True)),
                ('partner_concerned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safari_joint.PartnersModel')),
            ],
        ),
        migrations.CreateModel(
            name='TripBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_serial_number', models.CharField(blank=True, default=safari_joint.models.random_booking_chars, max_length=30, null=True)),
                ('day_of_booking', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('your_country', django_countries.fields.CountryField(max_length=2)),
                ('additional_note', models.CharField(blank=True, max_length=1000, null=True)),
                ('trip_booked', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safari_joint.TripAvailableDates')),
                ('trip_owner_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safari_joint.PartnersModel')),
            ],
        ),
        migrations.CreateModel(
            name='TripIdentificationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200)),
                ('tag_created_on', models.DateTimeField(auto_now_add=True)),
                ('tag_status', models.BooleanField(default=True)),
                ('tag_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripItenerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=10, null=True)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('trip_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safari_joint.TripIdentificationTag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripIteneraryChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_heading', models.CharField(max_length=10)),
                ('chart_day', models.IntegerField()),
                ('chart_start_at', models.CharField(max_length=100)),
                ('chart_start_attitude_meter', models.IntegerField()),
                ('chart_finish_at', models.CharField(max_length=100)),
                ('chart_finish_attitude_meter', models.IntegerField()),
                ('chart_minimum_time', models.IntegerField()),
                ('chart_maximum_time', models.IntegerField()),
                ('chart_distance_kilometer', models.IntegerField()),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safari_joint.PageContents')),
            ],
        ),
        migrations.AddField(
            model_name='tripavailabledates',
            name='trip_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safari_joint.TripIdentificationTag'),
        ),
        migrations.AddField(
            model_name='tripavailabledates',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerlogo',
            name='partner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safari_joint.PartnersModel'),
        ),
        migrations.AddField(
            model_name='partnergallerypicture',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safari_joint.PartnersModel'),
        ),
        migrations.AddField(
            model_name='partnergallerypicture',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedsmodel',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safari_joint.PartnersModel'),
        ),
        migrations.AddField(
            model_name='availableaccomodation',
            name='owner_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safari_joint.PartnersModel'),
        ),
        migrations.AddField(
            model_name='availableaccomodation',
            name='services',
            field=models.ManyToManyField(to='safari_joint.Service'),
        ),
        migrations.AddField(
            model_name='availableaccomodation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accomodationbookingmodel',
            name='room_booked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safari_joint.AvailableAccomodation'),
        ),
        migrations.AddField(
            model_name='accomodationbookingmodel',
            name='room_owner_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safari_joint.PartnersModel'),
        ),
    ]
