# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safari_joint', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accomodationbookingmodel',
            old_name='receipt_serial_number',
            new_name='receipt_serial',
        ),
        migrations.RenameField(
            model_name='tripbooking',
            old_name='receipt_serial_number',
            new_name='receipt_serial',
        ),
    ]
