# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safari_joint', '0003_auto_20170228_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodationbookingmodel',
            name='receipt_serial',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
