# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safari_joint', '0004_auto_20170228_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('ammount_in_percentage', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safari_joint.PartnersModel')),
            ],
        ),
        migrations.AddField(
            model_name='tripavailabledates',
            name='is_discounted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripdiscount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safari_joint.TripAvailableDates'),
        ),
    ]
