# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safari_joint', '0005_auto_20170301_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdiscount',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safari_joint.TripAvailableDates'),
        ),
    ]
