# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safari_joint', '0006_auto_20170301_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdiscount',
            name='ammount_in_percentage',
            field=models.FloatField(),
        ),
    ]
