# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-05 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('safari_joint', '0008_auto_20170303_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripavailabledates',
            name='cropping',
            field=image_cropping.fields.ImageRatioField(b'image', '430x360', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='tripavailabledates',
            name='trip_picture',
            field=models.ImageField(blank=True, null=True, upload_to=b'trip_images'),
        ),
    ]
