# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-05 17:43
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('safari_joint', '0009_auto_20170305_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripavailabledates',
            name='cropping',
            field=image_cropping.fields.ImageRatioField(b'trip_picture', '430x360', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
    ]
